### ISSUE TITLE
How to make a histogram

### ISSUE THREAD

**Issue by karamari** [Kanaries/pygwalker#15]
How do you make a histogram chart of one attribute (column)? (without pre-calculating the histogram data before putting the data into pygwalker, of course)

I fiddled with the UI for a while but couldn't find a way.
If it's not possible right now, I'd like it to be implemented.

Thanks

**Comment by ObservedObserver** [comment]
![example](https://user-images.githubusercontent.com/22167673/220356052-2a4b2472-fbcb-4f59-9533-dd39e6a0fd3f.gif)


Suppose you have a  field `score`, click the dropdown icon of the `score` field in the measure segment, there will be some transformations you can make, click the `bin` transformation option. and it create a new filed `bin(score)` in dimension segment. 

use `bin(score)` as the x-axis and `row count` as the y-axis and you can get a histogram.

It is not a perfect enough design, I am considering making the field editable so that you can write the expression `bin` or other computations more easily.

**Comment by karamari** [comment]
Thanks for the quick response! Awesome that it's implemented already, but yeah it'd be great if you could adjust the number of bins, and also if the labels showed exactly what value ranges are (e.g. 0-20, 20-40, 40-60)

**Comment by ilyanoskov** [comment]
I second this, it would be very helpful to be able to select the number of bins for a histogram. I need the histogram in one of the projects I use, but can't use Pygwalker for it yet...

**Comment by ibobak** [comment]
I have two problems with bins:
1. I can't find where is this setting of number of bins? how to get there?
2. why the histogram is not maximized by default?

**Comment by ibobak** [comment]
Looks like I found where it is:  at the creation time of a new field.
But if I want to change the existing field - I cannot do this.
