### ISSUE TITLE
[BUG] pygwalker bug report: interactive UI doesn't show up

### ISSUE THREAD

**Issue by PhilippeDataScienc** [Kanaries/pygwalker#346]
**Describe the bug**
When trying to load a df with pygwalker inside Jupyter Notebook to display the interactive UI, a HTML message is displayed instead of the interactive UI.
`import pandas as pd`
`import pygwalker as pyg`
`df = pd.read_csv("toto.csv", sep=',')`

`gwalker = pyg.walk(df)`

> `Box(children=(HTML(value='<div id="ifr-pyg-1" style="height: auto">\n    <head>\n        <meta http-equiv="Con…`

**To Reproduce**
1. Go to 'jupyter notebook'
2. Click on 'load a csv into a pandas dataFrame'
3. type `gwalker = pyg.walk(df)`

**Expected behavior**
A graphical and interactive UI shows up !

**Screenshots**
![image](https://github.com/Kanaries/pygwalker/assets/86467937/3cf027d6-3228-4c90-95dd-0e503c2338c8)

**Versions**
- pygwalker version: 0.3.17
- python version: 3.11
- browser: Brave

**Additional context**

**Comment by longxiaofei** [comment]
Hi, @PhilippeDataScienc 

Could you tell me the version of your notebook or jupyterlab?

I will try to reproduce it.

Also, Could you try running the code below and tell me what the output is?

```python
from IPython.display import display
import ipywidgets as widgets

button = widgets.Button(description="Click Me!")
output = widgets.Output()

display(button, output)

def on_button_clicked(b):
    with output:
        print("Button clicked.")

button.on_click(on_button_clicked)
```

Thanks.

**Comment by PhilippeDataScienc** [comment]
your code snippet works for me ! I have a click me button displayed!
![image](https://github.com/Kanaries/pygwalker/assets/86467937/7c61fbe8-88b5-4b45-a534-176fb827f749)

My jupyterlab version is: 4.0.9
![image](https://github.com/Kanaries/pygwalker/assets/86467937/f6c9d17f-376a-4990-9d6e-41659ed588da)

Problem seems to be solved with your code snippet, maybe I had an import missing ?
![image](https://github.com/Kanaries/pygwalker/assets/86467937/3f85a7fb-a3b7-4515-9134-0ca35269e938)

**Comment by longxiaofei** [comment]
I guessed that it was your first time using the pygwalker process, and I successfully reproduced the bug.

Since you haven't installed ipywidgets before, when the Jupyter kernel was already running, installing pygwalker (which relies on ipywidgets for rendering) caused the notebook to not establish communication with ipywidgets, resulting in the unsuccessful rendering of pygwalker's UI. 

However, when you close the kernel and refresh the page, JupyterLab should establish communication with ipywidgets again (or for some other reason, JupyterLab establishes communication with ipywidgets), so pygwalker could be re-rendered.

This bug will not occur again when you use pygwalker in the future.
