### ISSUE TITLE
[Feat] How to display a bar chart instead of a heatmap?

### ISSUE THREAD

**Issue by Json-Woo** [Kanaries/pygwalker#39]
Noticed an issue from [https://discord.com/channels/987366424634884096/1057481447541325885]()

> I'm trying out pygwalker and I've noticed that some of my fields land in the 'blue' portion of the field list, which appear to be treated as buckets, while some land in the 'green' portion of the field list, which look like they're treated as numbers. In the dataframe I'm loading, one of my fields is in the blue bucket category and the other is in the green number category. Both fields are int64 data types with no nulls. 
> 
> How should I understand this behavior and how can I modify it?
> 
> UPD: It does look like I can drag the field from blue to green, but even if I choose 'Sum' it is still treated as a bucket, so what should look like a bar chart instead resembles a heatmap.

**Comment by Asm-Def** [comment]
Just like in tableau, each field in graphic-walker has a semantic type which can be either quantitative, ordinal, nominal, or temporal. 

When the number of distinct values ​​of a certain field is relatively small, pygwalker will recognize the field as ordinal rather than quantitative, so a heatmap will be displayed instead of a bar chart.

Fortunately, this pr https://github.com/Kanaries/pygwalker/pull/38 has enabled editing the semantic type at any time in the UI, and has been released in `0.1.4.3`.

<div><img width="40%" src="https://user-images.githubusercontent.com/8137814/221320221-7e518889-9382-4841-b3cc-57de1c4242fa.png" />
<img width="40%" src="https://user-images.githubusercontent.com/8137814/221319131-e44f9d60-81ab-46f6-ade9-7954ee4143b3.png" />
</div>

And then we get the correct bar chart.
<img width="40%" src="https://user-images.githubusercontent.com/8137814/221319760-3d340c44-b315-4e68-93e0-a156ae262dd8.png" />

Simply upgrade to the latest version to have a try.
