### ISSUE TITLE
How would I aggregate only one field?

### ISSUE THREAD

**Issue by danre07** [Kanaries/pygwalker#42]
When I turn on the aggregation function, it turns my plot into a single point, which is not very helpful. Is there a way where I can see the average of field but leaving the other field as raw values -- this is especially helpful when I have categorical data.

**Comment by Asm-Def** [comment]
It's because of the different behaviors of different analytic types.

Leaving a field unaggregated means that this field is treated as a 'dimension' instead of a 'measure'. You can drag the field from the green region (measures) to the blue region (dimensions), or click the drop-down list on the field and click `bin10` to generate a binning dimension if this field has too many distinct values to analyze.


https://user-images.githubusercontent.com/8137814/221472087-c5076cc0-6f5a-405b-b12a-9b04c1104a89.mp4
