### ISSUE TITLE
Data inferring - dates, datetimes, etc.

### ISSUE THREAD

**Issue by Vfisa** [Kanaries/pygwalker#423]
Currently Pygwalker assigns to types of data:
facts(#) and dimensions. 

I would love it to recognize dates, datetimes and other time-related dimensions, so it would allow:

- Datetime filtering
- Datetime slicing with a hierarchy (year-month-day-etc.)
- Relative and absolute datetime functions

I have tried to load data in a standard datetime format but no luck.

**Comment by longxiaofei** [comment]
Hi @Vfisa 

In the past, pygwalker would infer date strings as temporal.

example:
```
2022-10-10
2022-10-10 10:10:10
2022-11-11T00:00:00
...
```

However, after feedback from users,they prefer pygwalker to give the original type of data, instead of perform some implicit inferences.

So, You need to manually convert the data type in the UI.

example:

https://github.com/Kanaries/pygwalker/assets/28337703/7d9255fd-a48b-4c81-a2fd-f1d86906d78f
