### ISSUE TITLE
Poetry `add duckdb pygwalker` fails to resolve dependencies.

### ISSUE THREAD

**Issue by gregglind** [Kanaries/pygwalker#544]
As Duckdb continues to develop (and increase version, consider relaxing the constraint in [`pyproject.toml`](https://github.com/Kanaries/pygwalker/blob/9cd4fb8ccfd3874d3a7663ee2997e4c4c628da01/pyproject.toml#L22C5-L22C22) to a Semver on ^0.  

See:  https://python-poetry.org/docs/dependency-specification/ for details.

**Comment by hermansje** [comment]
Before a the first major release, breaking changes can be introduced in minor updates according to semver. This is something DuckDB also has also used (e.g. between 0.9.x and 0.10.x).
But I agree that the constraint could be relaxed to enforce a minor version, currently `^0.10`, which would allow using the currently latest `0.10.2` release instead of `0.10.1`.

**Comment by longxiaofei** [comment]
When upgrading from duckdb 0.8.0 to 0.9.0,  due to changes in duckdb function logic, pygwalker cannot work.

So I fixed the duckdb version.

Thanks for your suggestion, I will change it to `^0.10`.
