### ISSUE TITLE
[Feat] Ability to pre-set UI & charts

### ISSUE THREAD

**Issue by ilyanoskov** [Kanaries/pygwalker#60]
Dear Kanaries Team,

Thank you for such an amazing project, it is very useful! 

One feature that would be very helpful is to be able to pre-set multiple charts / tabs from a loaded config file. Right now, one has to manually upload the config file to get the charts configured. 

We are now building many many dashboards with your project, and having to re-configure charts each time we reload is a huge blocker.

Thank you very much in advance 🙏

**Comment by Asm-Def** [comment]
Thanks for your feedback! Coincidentally, I am working on it. Please join our [Slack](https://join.slack.com/t/kanaries-community/shared_invite/zt-1pcosgbua-E_GBPawQOI79C41dPDyyvw) or [Discord](https://discord.gg/Z4ngFWXz2U) channel to track our progress.

**Comment by Asm-Def** [comment]
Hello, sorry for the late reply.
I noticed that you've already found the PR for importing and exporting charts. https://github.com/Kanaries/pygwalker/pull/73#issue-1615629744 .
To avoid confusion, here is a note that this feature has been pre-released since [`pygwalker==0.1.6.2a0`](https://pypi.org/project/pygwalker/0.1.6.2a0), though the PR has been closed when cleaning the large files in the commit history.

**Comment by longxiaofei** [comment]
Hi, @ilyanoskov, so long has passed, It's not clear to me if you're still using pygwalker.

pygwalker(0.2.0) has been released, some of these features may meet your needs.

[pygwalker0.2 features](https://docs.kanaries.net/en/pygwalker/changelog/pygwalker-0-2)
